### ISSUE TITLE
On lp clarkson

### ISSUE THREAD

**Issue by Ajayreddy17** [dacin21/dacin21_codebook#2]
lp clarkson returns x, but it has one extra element generally 1, 2 what does they mean?

My issues was if A = [[-1, -1, 0], [-1, 0, -1],  [0, -1, -1]],  B = [-1, -1, -1]  and C = [-1, -1, -1] .  we except output x = [1 0 1] or [0 1 1] or [1 1 0], but i was getting [1 1 1] as output.

**Comment by dacin21** [comment]
The output of the LP algorithms is in projective coordinates, In your example, you should get [1, 1, 1, 2], which corresponds to x=[1/2, 1/2, 1/2], the optimal point with objective value -3/2. In general, you have to divide all choordinates by the last value (the "one extra element").

The advantage of projective coordinates is that you can work with integers, rather than rational numbers.
